# Generated by Django 6.0.1 on 2026-01-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codinome', models.CharField(blank=True, help_text="Nome de rua (Ex: 'Street Samurai')", max_length=50)),
                ('metatipo', models.CharField(choices=[('Humano', 'Humano'), ('Elfo', 'Elfo'), ('Anão', 'Anão'), ('Ork', 'Ork'), ('Troll', 'Troll')], default='Humano', max_length=20)),
                ('dano_fisico', models.IntegerField(default=0, help_text='Dano Físico atual')),
                ('dano_atordoamento', models.IntegerField(default=0, help_text='Dano de Atordoamento (Stun) atual')),
            ],
        ),
        migrations.CreateModel(
            name='Pericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Armas de Fogo, Furtividade', max_length=50)),
                ('atributo_base', models.CharField(choices=[('BOD', 'Constituição (BOD)'), ('AGI', 'Agilidade (AGI)'), ('REA', 'Reação (REA)'), ('STR', 'Força (STR)'), ('WIL', 'Vontade (WIL)'), ('LOG', 'Lógica (LOG)'), ('INT', 'Intuição (INT)'), ('CHA', 'Carisma (CHA)'), ('EDG', 'Limite (Edge)'), ('MAG', 'Magia/Ressonância')], max_length=3)),
                ('valor', models.IntegerField(default=0)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pericias', to='runner_sheet.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('BOD', 'Constituição (BOD)'), ('AGI', 'Agilidade (AGI)'), ('REA', 'Reação (REA)'), ('STR', 'Força (STR)'), ('WIL', 'Vontade (WIL)'), ('LOG', 'Lógica (LOG)'), ('INT', 'Intuição (INT)'), ('CHA', 'Carisma (CHA)'), ('EDG', 'Limite (Edge)'), ('MAG', 'Magia/Ressonância')], max_length=3)),
                ('valor', models.IntegerField(default=1)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='runner_sheet.personagem')),
            ],
            options={
                'unique_together': {('personagem', 'nome')},
            },
        ),
    ]
