# Generated by Django 6.0.1 on 2026-01-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='runners_avatars/'),
        ),
    ]
