# Generated by Django 6.0.1 on 2026-01-28 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_sheet', '0002_personagem_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Ares Predator V', max_length=100)),
                ('dano', models.CharField(help_text='Ex: 8P', max_length=10)),
                ('ap', models.IntegerField(default=0, help_text='Penetração de Armadura (Ex: -1)')),
                ('pericia_associada', models.ForeignKey(help_text='Qual perícia essa arma usa?', on_delete=django.db.models.deletion.CASCADE, to='runner_sheet.pericia')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='runner_sheet.personagem')),
            ],
        ),
    ]
