# Generated by Django 6.0.1 on 2026-01-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_sheet', '0003_arma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pericia',
            old_name='valor',
            new_name='pontos',
        ),
        migrations.AlterUniqueTogether(
            name='atributo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pericia',
            name='atributo_base',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='codinome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='dano_atordoamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='dano_fisico',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='metatipo',
            field=models.CharField(choices=[('HUM', 'Humano'), ('ELF', 'Elfo'), ('ORK', 'Ork'), ('DWF', 'Anão'), ('TRL', 'Troll')], default='HUM', max_length=3),
        ),
    ]
