# Generated by Django 6.0.1 on 2026-01-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_sheet', '0004_rename_valor_pericia_pontos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='pericia_associada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner_sheet.pericia'),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='nome',
            field=models.CharField(choices=[('Corpo', 'Corpo (BOD)'), ('Agilidade', 'Agilidade (AGI)'), ('Reação', 'Reação (REA)'), ('Força', 'Força (STR)'), ('Vontade', 'Vontade (WIL)'), ('Lógica', 'Lógica (LOG)'), ('Intuição', 'Intuição (INT)'), ('Carisma', 'Carisma (CHA)'), ('Edge', 'Edge (EDG)'), ('Mágica', 'Mágica (MAG)'), ('Ressonância', 'Ressonância (RES)')], default='Corpo', max_length=50),
        ),
        migrations.AlterField(
            model_name='pericia',
            name='atributo_base',
            field=models.CharField(choices=[('Agilidade', 'Agilidade'), ('Corpo', 'Corpo'), ('Reação', 'Reação'), ('Força', 'Força'), ('Lógica', 'Lógica'), ('Intuição', 'Intuição'), ('Carisma', 'Carisma'), ('Vontade', 'Vontade'), ('Mágica', 'Mágica'), ('Ressonância', 'Ressonância')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('Astral', 'Astral (INT)'), ('Atletismo', 'Atletismo (AGI)'), ('Biotecnologia', 'Biotecnologia (LOG)'), ('Combate Prox', 'Combate Próximo (AGI)'), ('Trambique', 'Trambique (CHA)'), ('Conjuracao', 'Conjuração (MAG)'), ('Eletronica', 'Eletrônica (LOG)'), ('Engenharia', 'Engenharia (LOG)'), ('Armas de Fogo', 'Armas de Fogo (AGI)'), ('Influencia', 'Influência (CHA)'), ('Ao Ar Livre', 'Ao Ar Livre (INT)'), ('Percepcao', 'Percepção (INT)'), ('Pilotagem', 'Pilotagem (REA)'), ('Feiticaria', 'Feitiçaria (MAG)'), ('Furtividade', 'Furtividade (AGI)'), ('Cracking', 'Cracking (LOG)'), ('Tasking', 'Tasking (RES)'), ('Exoticas', 'Armas Exóticas (AGI)')], max_length=50),
        ),
    ]
