# Generated by Django 6.0.1 on 2026-01-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_sheet', '0005_alter_arma_pericia_associada_alter_atributo_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='max_fisico',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='personagem',
            name='max_stun',
            field=models.IntegerField(default=10),
        ),
    ]
