# Generated by Django 6.0.1 on 2026-01-31 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_sheet', '0006_personagem_max_fisico_personagem_max_stun'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='defesa_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personagem',
            name='karma',
            field=models.IntegerField(default=0, help_text='Karma Total'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='nuyen',
            field=models.IntegerField(default=0, help_text='Dinheiro ($)'),
        ),
        migrations.AlterField(
            model_name='arma',
            name='ap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arma',
            name='dano',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='arma',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arma',
            name='pericia_associada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='runner_sheet.pericia'),
        ),
        migrations.AlterField(
            model_name='pericia',
            name='atributo_base',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Armadura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Jaqueta Blindada', max_length=100)),
                ('valor_defesa', models.IntegerField(default=2, help_text='Valor que soma na Defesa')),
                ('equipada', models.BooleanField(default=True)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armaduras', to='runner_sheet.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Cyberware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Olhos Cibernéticos', max_length=100)),
                ('nivel', models.IntegerField(default=1)),
                ('essencia', models.FloatField(default=0.1, help_text='Custo de Essência')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyberware', to='runner_sheet.personagem')),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Medkit, Commlink', max_length=100)),
                ('qtd', models.IntegerField(default=1)),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='runner_sheet.personagem')),
            ],
        ),
    ]
