# Generated by Django 6.0.1 on 2026-01-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_sheet', '0007_personagem_defesa_total_personagem_karma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='arquetipo',
            field=models.CharField(choices=[('SAM', 'Samurai Urbano (Combate)'), ('MAG', 'Mago/Xamã (Magia)'), ('DEC', 'Decker (Hacker)'), ('RIG', 'Rigger (Drones/Veículos)'), ('FAC', 'Face (Social)'), ('ADE', 'Adepto (Combate Mágico)')], default='SAM', help_text='Define o estilo de jogo', max_length=3),
        ),
        migrations.AlterField(
            model_name='armadura',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='armadura',
            name='valor_defesa',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='atributo',
            name='nome',
            field=models.CharField(choices=[('Corpo', 'Corpo (BOD)'), ('Agilidade', 'Agilidade (AGI)'), ('Reação', 'Reação (REA)'), ('Força', 'Força (STR)'), ('Vontade', 'Vontade (WIL)'), ('Lógica', 'Lógica (LOG)'), ('Intuição', 'Intuição (INT)'), ('Carisma', 'Carisma (CHA)'), ('Trunfo', 'Trunfo (EDG)'), ('Mágica', 'Mágica (MAG)'), ('Ressonância', 'Ressonância (RES)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='essencia',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='cyberware',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pericia',
            name='nome',
            field=models.CharField(choices=[('Armas de Fogo', 'Armas de Fogo (AGI)'), ('Armas Exóticas', 'Armas Exóticas (AGI)'), ('Astral', 'Astral (INT)'), ('Atletismo', 'Atletismo (AGI)'), ('Biotec', 'Biotecnologia (LOG)'), ('Combate Prox', 'Combate Próximo (AGI)'), ('Conjuracao', 'Conjuração (MAG)'), ('Cracking', 'Cracking (LOG)'), ('Eletronica', 'Eletrônica (LOG)'), ('Encantar', 'Encantar (MAG)'), ('Engenharia', 'Engenharia (LOG)'), ('Exteriores', 'Exteriores (INT)'), ('Feiticaria', 'Feitiçaria (MAG)'), ('Furtividade', 'Furtividade (AGI)'), ('Influencia', 'Influência (CHA)'), ('Percepcao', 'Percepção (INT)'), ('Pilotagem', 'Pilotagem (REA)'), ('Tarefa', 'Tarefa (RES)'), ('Trapaca', 'Trapaça (CHA)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='metatipo',
            field=models.CharField(choices=[('HUM', 'Humano (Padrão)'), ('ELF', 'Elfo (Agi+1, Car+2)'), ('ORK', 'Ork (Cor+3, For+2)'), ('DWF', 'Anão (Cor+2, For+2, Von+1)'), ('TRL', 'Troll (Cor+4, For+4, -1 Agi/Log/Car)')], default='HUM', max_length=3),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='nuyen',
            field=models.IntegerField(default=0),
        ),
    ]
