# Generated by Django 6.0.1 on 2026-01-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner_sheet', '0008_personagem_arquetipo_alter_armadura_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='estilo_vida',
            field=models.CharField(choices=[('RUA', 'Rua (Custo: 0¥) - Sem teto, perigoso.'), ('FUV', 'Favelado (Custo: 500¥) - Squatter, caixas ou contêineres.'), ('BAI', 'Baixo (Custo: 2.000¥) - Apartamento simples, comida barata.'), ('MED', 'Médio (Custo: 5.000¥) - Confortável, seguro.'), ('ALT', 'Alto (Custo: 10.000¥) - Luxo moderado, boa segurança.'), ('LUX', 'Luxo (Custo: 100.000¥+) - Elite corporativa.')], default='MED', max_length=3),
        ),
    ]
